### ISSUE TITLE
Photoswipe support

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/gallery_tiler#1]
Is it possible to support Photoswipe?

**Comment by indigoxela** [comment]
> Is it possible to support Photoswipe?

Interesting question... Might be worth a try. A module exists, that provides the library, so in theory this could work.

**Comment by indigoxela** [comment]
This needs a lot more than I had hoped... but an experimental branch is available for testing: https://github.com/backdrop-contrib/gallery_tiler/tree/photoswipe

Note: do not use on production sites, yet!

**Comment by indigoxela** [comment]
@djzwerg it should be noted, that there won't be much progress here, unless you test the new functionality – you requested it. :smirk:

**Comment by djzwerg** [comment]
@indigoxela sorry I didn't recognize the link. I'm going to test it later this day.

**Comment by djzwerg** [comment]
@indigoxela Photoswipe module works! 

Thanks for your great and fast work!

**Comment by indigoxela** [comment]
> Photoswipe module works!

Great! :smirk: I hope you meant "Gallery Tiler module works".

In case you speak German, there's a [mini-tutorial](https://backdrop-cms.de/blog/bildergalerien-aus-bildfeldern-mit-gallery-tiler) about this module.

**Comment by djzwerg** [comment]
@indigoxela of course, I meant "Gallery Tiler module works with support for PhotoSwipe" ;-)
