### ISSUE TITLE
Configuration Documentation

### ISSUE THREAD

**Issue by Retsell** [backdrop-contrib/gallery_tiler#3]
Says "Easy to configure", but how?  There are no instructions for use, and I can't find any configuration parameters anywhere. I have multi-image fields in a content type, but see no reference to gallery-tiler settings for displaying it.

**Comment by indigoxela** [comment]
> Says "Easy to configure", but how?

It's a **field formatter**, so you choose the format in your field's display setting. And there are all the settings. (Example: admin/structure/types/manage/your-content-type/display/default)

Here's a [blog post in German](https://backdrop-cms.de/blog/bildergalerien-aus-bildfeldern-mit-gallery-tiler) - try with Google translate. But the screenshots should already explain everything.
