### ISSUE TITLE
Field block doesn't respect gallery settings

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/gallery_tiler#4]
Thanks for this cool formatter! Currently I'm trying to display an image field using the "Tiled gallery" format as block in a layout. When I place the field as a block and adjust the settings, they are not respected, no matter which Gallery type, gap and so on. What I see as result, is more or less a plain list of images.

**Comment by olafgrabienski** [comment]
On further examination I found out: The issue happens if the image field is *hidden* in the Manage Display configuration of the content type (`admin/structure/types/manage/my-type/display/default`). If I choose instead to *display* the field there and adjust the gallery settings at this very place, the gallery is displayed as expected. And the other gallery (placed as block) seems to inherit the settings from the Manage Display configuration. Conclusion for the time being: I can't show the gallery independently as a block in a layout.

**Comment by indigoxela** [comment]
Can you please check if the file **gallery-tiler.css** is loaded on the page (inspect source code)

My suspicion is that hook_field_formatter_view() does not run if the field is set to hidden. So maybe what you want isn't possible at all.

But there are always alternatives.

**Comment by indigoxela** [comment]
Hm, nope, it has nothing to do with hook_field_formatter_view(), the problem arises with field_formatter_settings_get_instance_display_settings() - which returns an empty result for field blocks.

**Comment by indigoxela** [comment]
@olafgrabienski ... it's impossible.

The field formatter grabs the settings for the field as configured - that's completely hidden in your case. So no formatter settings for the combo entity_type + field_name + bundle + view_mode exists. We can not know how to display the field, when there are no active settings (besides hidden).

Use a view instead.

This is the only thing we have:
```
    'default' => 
    array (
      'label' => 'hidden',
      'type' => 'hidden',
      'weight' => '1',
      'settings' => 
      array (
      ),
    ),
```
So field_formatter_settings_get_instance_display_settings() returns an empty array. There's nothing this module can do about that.

**Comment by olafgrabienski** [comment]
Oh, that's interesting! Is it a core issue then? (Wondering why the gallery settings appear in the block configuration.)

**Comment by indigoxela** [comment]
> Is it a core issue then?

Might be. The formatter settings get written into the layout config file - and that info is not accessible for the formatter. The formatter can not know where it gets applied (where to search for its settings).

And I wouldn't know how field_formatter_settings_get_instance_display_settings() (core function) could figure that out, too.

**Comment by indigoxela** [comment]
Some more digging...

Necessary things happen in the module's template preprocessor. But in that function the layout's settings aren't accessible at all.
The field block class creates a pseudo field instance - without the preprocessor applied, so important settings are missing.

I wouldn't know how to solve that without core changes, I wouldn't even know what changes in core are necessary. So this is a "won't fix".

I'm assuming, this affects all field formatters with template preprocessors.
@olafgrabienski if you find a solution, feel free to re-open this issue.

**Comment by olafgrabienski** [comment]
Thanks for your feedback! I'm definitely curious what Backdrop core could do better and/or how other modules handle such a case, but I guess that's above my skills. I'll stick with the workaround to use a view, which is fine for me.
