### ISSUE TITLE
Tiled gallery not working in Views (with contextual filter)

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/gallery_tiler#8]
As yoiu can see here how tiled gallery looks as a field formatter (top) and as Views output (bottom) it doesn't work with Views:
![grafik](https://user-images.githubusercontent.com/49948628/203560502-97c5c12c-8a00-428e-9253-aa830e25b47a.png)

Steps to reproduce:

1. Create content type
2. Add image field with more than 1 possible entities
3. Add a node
4. Add a view (block, unformatted) with the image field - formatter "Tiled gallery"
5. Add the contextual filter Node:Node ID to your view providing Node ID by URL
6. Add the Views block to your layout
7. Go to your node URL

**Comment by indigoxela** [comment]
Tiled galleries aren't supposed to work with Views. There's no views display plugin.

If you **want** to use it with views and fields (discouraged!), you have to check the "Use field template" setting in the views' style settings.

That's exactly what the help text says:

> This field formatter only works if "Use field template" is selected in the style settings below, and has limited settings in views.

Alternatively use a custom display mode for your content type and switch from Fields to Content in your view.

**Comment by djzwerg** [comment]
Oh thanks @indigoxela - is there a plan to provide full Views support?

**Comment by indigoxela** [comment]
> is there a plan to provide full Views support?

No plans. I simply don't need it and views support is too much effort to just do it "for fun".
